version: '3'
services:
  terraform:
    container_name: terraform
    build:
      context: .
      dockerfile: Dockerfile
      # image: hashicorp/terraform:1.4.6
      # env_file:
      # - .env
    volumes:
      - ~/.aws:/root/.aws:ro
      - ./terraform:/terraform
      - ./.bashrc:/root/.bashrc
    working_dir: /terraform
    entrypoint: bash
    tty: true
