version: '3'
services:
  terraform:
    container_name: terraform
    image: hashicorp/terraform:1.4.6
    env_file:
      - .env
    volumes:
      - ~/.aws:/root/.aws:ro
      - ./terraform:/terraform
    working_dir: /terraform
    entrypoint: ash
    tty: true
